AWSTemplateFormatVersion: '2010-09-09'

Description: 'State: Client security group'

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'Parent Stacks'
      Parameters:
      - ParentVPCStack

Parameters:
  ParentVPCStack:
    Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
    Type: String

Resources:
  ClientSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Ref 'AWS::StackName'
      VpcId: {'Fn::ImportValue': !Sub '${ParentVPCStack}-VPC'}
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ClientSecurityGroup'

Outputs:
  TemplateID:
    Description: 'template id.'
    Value: 'state/client-sg'

  TemplateVersion:
    Description: 'template version.'
    Value: '0.0.1'

  StackName:
    Description: 'Stack name.'
    Value: !Sub '${AWS::StackName}'
    
  ClientSecurityGroup:
    Description: 'Use this Security Group to reference client traffic.'
    Value: !Ref ClientSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ClientSecurityGroup'
